In [3]:
import scipy
import numpy as np

In [5]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
scipy.linalg.inv(A)

array([[ 1., -0., -0., -0., -0.],
       [ 0.,  1., -0., -0., -0.],
       [ 0.,  0.,  1., -0., -0.],
       [ 0.,  0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [8]:
B = np.array([[1, 2],
              [2, 3]])

In [9]:
scipy.linalg.inv(B)

array([[-3.,  2.],
       [ 2., -1.]])

In [10]:
scipy.linalg.eigh(B)

(array([-0.23606798,  4.23606798]),
 array([[-0.85065081,  0.52573111],
        [ 0.52573111,  0.85065081]]))

In [11]:
B.T

array([[1, 2],
       [2, 3]])

In [12]:
scipy.linalg.det(B)

np.float64(-1.0)

In [13]:
scipy.linalg.solve?

Signature:
scipy.linalg.solve(
    a,
    b,
    lower=False,
    overwrite_a=False,
    overwrite_b=False,
    check_finite=True,
    assume_a=None,
    transposed=False,
)
Docstring:
Solve the equation ``a @ x = b`` for  ``x``,
where `a` is a square matrix.

If the data matrix is known to be a particular type then supplying the
corresponding string to ``assume_a`` key chooses the dedicated solver.
The available options are

=============================  ================================
 diagonal                       'diagonal'
 tridiagonal                    'tridiagonal'
 banded                         'banded'
 upper triangular               'upper triangular'
 lower triangular               'lower triangular'
 symmetric                      'symmetric' (or 'sym')
 hermitian                      'hermitian' (or 'her')
 symmetric positive definite    'positive definite' (or 'pos')
 general                        'general' (or 'gen')
=============================  =================

In [14]:
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
B

array([[1, 2],
       [2, 3]])

In [16]:
v = np.array([-1, -1])

In [18]:
scipy.linalg.solve(B, v)

array([ 1., -1.])

Find a root of the following function
$$f(x) = (x - 1)(x - 6).$$

In [37]:
def f(x):
    return (x - 1)*(x - 6)

def df(x):
    return (x - 6) + (x - 

scipy.optimize.root_scalar(f, x0 = 0.0, fprime=df, method="newton", bracket = (4, 10))
# import matplotlib.pyplot as plt

# xs = np.linspace(0, 10, 100)
# plt.plot(xs, f(xs), marker="x")

      converged: True
           flag: converged
 function_calls: 10
     iterations: 5
           root: 1.0
         method: newton