## Exercise 2-2

Try the different flavours of slicing, using start, end and step: starting from a `linspace`, try
to obtain odd numbers counting backwards, and even numbers counting forwards.

Try to obtain the slices as shown below

![img](mat_slices.png)

In [22]:
import numpy as np
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [16]:
b = np.arange(0, 51, 10)[:, np.newaxis]
b

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [24]:
a = a + b

In [25]:
a[0, 3:5]

array([3, 4])

In [26]:
a[0, 3:5]

array([3, 4])

In [27]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [28]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [29]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [31]:
a[[2, 4], :][:, [0, 2, 4]]

array([[20, 22, 24],
       [40, 42, 44]])

In [51]:
a = np.ones((3, 3)) + np.arange(3)
a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [37]:
np.sum(a)

np.float64(18.0)

In [39]:
np.sum(a, axis=1)

array([6., 6., 6.])

In [40]:
a.min()

np.float64(1.0)

In [41]:
a.min(axis=0)

array([1., 2., 3.])

In [42]:
a.max(axis=1)

array([3., 3., 3.])

In [43]:
a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [44]:
a.flatten()

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [45]:
a.ravel()

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [47]:
a.ravel()[:] = 0.0

In [48]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.transpose(a)

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [53]:
a.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [55]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
a*b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
a@b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [60]:
np.matrix(a)*np.matrix(b)

matrix([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [61]:
np.einsum("ij, jk", a, b)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [62]:
np.cos(a)

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

In [63]:
np.linalg.inv(a)

LinAlgError: Singular matrix

In [64]:
np.linalg.det(a)

np.float64(0.0)